name: CI

on:
  push:
    branches: [ develop, release ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'
      - '.remarkrc'
      - '*.md'
      - '*.yml'
      - '*.json'
  pull_request:
    branches: [ develop, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/vpk_linux32
          ~/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/libvstdlib.so
          ~/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/libtier0.so
          ~/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/filesystem_stdio.so
          ~/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/libtcmalloc_minimal.so.4
        key: ${{ runner.os }}-cache-2
    - name: Install dependencies (with Steam)
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        echo steam steam/question select "I AGREE" | sudo debconf-set-selections
        echo steam steam/license note '' | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install steamcmd
        /usr/games/steamcmd +login anonymous +download_depot 232250 232256 +quit
        sudo bash -c 'cat <<\EOF > /usr/local/bin/vpk
        #!/bin/bash
        VPK_LINUX=/home/runner/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/vpk_linux32
        VALVE_LIB_DIR=/home/runner/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin
        LD_LIBRARY_PATH="${VALVE_LIB_DIR}:${LD_LIBRARY_PATH}" "${VPK_LINUX}" "${@}"
        EOF'
        sudo chmod +x /usr/local/bin/vpk
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        sudo bash -c 'cat <<\EOF > /usr/local/bin/vpk
        #!/bin/bash
        VPK_LINUX=/home/runner/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin/vpk_linux32
        VALVE_LIB_DIR=/home/runner/.steam/steamcmd/linux32/steamapps/content/app_232250/depot_232256/bin
        LD_LIBRARY_PATH="${VALVE_LIB_DIR}:${LD_LIBRARY_PATH}" "${VPK_LINUX}" "${@}"
        EOF'
        sudo chmod +x /usr/local/bin/vpk
    - name: Build mastercomfig
      run: dev/release.sh
      env:
        prerelease: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mastercomfig
        if-no-files-found: error
        path: |
          dev/prerelease/presets
          dev/prerelease/addons
          dev/prerelease/comfig
          dev/prerelease/template
