name: CI

on:
  push:
    branches: [ develop, release ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'
      - '.remarkrc'
      - '*.md'
      - '*.yml'
      - '*.json'
  pull_request:
    branches: [ develop, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        path: |
          /home/runner/.steam
        key: ${{ runner.os }}-cache
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        echo steam steam/question select "I AGREE" | sudo debconf-set-selections
        echo steam steam/license note '' | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install steamcmd dos2unix
        /usr/games/steamcmd +login anonymous +force_install_dir ./tf2 +download_depot 232250 232256 +quit
        sudo bash -Ec '
        export VPK_LINUX=$(find "${HOME}" -type f -iname "vpk_linux32" -print | head -n 1)
        export VALVE_LIB_DIR=$(dirname "${VPK_LINUX}")
        cat <<EOF > /usr/local/bin/vpk
        #!/bin/bash
        VPK_LINUX=${VPK_LINUX}
        VALVE_LIB_DIR=${VALVE_LIB_DIR}
        EOF'
        sudo bash -c 'cat <<\EOF >> /usr/local/bin/vpk
        LD_LIBRARY_PATH="${VALVE_LIB_DIR}:${LD_LIBRARY_PATH}" "${VPK_LINUX}" "${@}"
        EOF'
        sudo chmod +x /usr/local/bin/vpk
    - name: Build mastercomfig
      run: dev/release.sh
      env:
        prerelease: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mastercomfig
        if-no-files-found: error
        path: |
          dev/prerelease/presets
          dev/prerelease/addons
          dev/prerelease/comfig
          dev/prerelease/template
